import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import { Button, Toast } from "@heroui/react";
import { Navbar } from "@/components/navbar/Navbar";
import AuthProvider from "@/context/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <Toast.Provider /><header>
            <Navbar
              brand={
                <>
                  <Link
                    href="/"
                    className="font-bold text-4xl gradient-bg-2 text-transparent bg-clip-text!"
                  >
                    Skillsphere
                  </Link>
                </>
              }
              items={[
                { label: "Home", href: "/" },
                { label: "Courses", href: "/courses" },
                { label: "Contact", href: "/contact" },
              ]}
              rightContent={
                <>
                  <Link href="/login">
                    <Button variant="ghost">Login</Button>
                  </Link>
                  <Link href="/sign-up">
                    <Button className={"gradient-bg-2"}>Sign Up</Button>
                  </Link>
                </>
              }
            />
          </header>
          {children}
        </AuthProvider>

      </body>
    </html>
  );
}
